#!/bin/bash
##################################################
# VOD Uploader Docker Container                  #
# Auto-update template script                    #
##################################################
# This script fetches latest versions and        #
# generates Dockerfile and release.json          #
##################################################

set -e

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "${SCRIPT_DIR}")"

echo "========================================"
echo "  VOD Uploader Auto-Update Script"
echo "========================================"

### FETCH LATEST VERSIONS ###

echo "**** fetching latest Alpine version ****"
ALPINE_VERSION=$(curl -sX GET "https://registry.hub.docker.com/v2/repositories/library/alpine/tags" \
   | jq -r 'select(.results != null) | .results[]["name"]' \
   | sort -t "." -k1,1n -k2,2n -k3,3n | grep "^3\." | grep -v "edge" | tail -n1)
echo "Alpine: ${ALPINE_VERSION}"

echo "**** fetching latest LinuxServer baseimage version ****"
BASEIMAGE_VERSION=$(curl -sX GET "https://api.github.com/repos/linuxserver/docker-baseimage-alpine/releases/latest" \
   | jq -r '.tag_name')
echo "Baseimage: ${BASEIMAGE_VERSION}"

### APP SETTINGS ###
APP="docker-uploader"
APPFOLDER="${ROOT_DIR}"
PICTURE="./images/${APP}.png"

FINALIMAGE="ghcr.io/linuxserver/baseimage-alpine"

### GENERATE release.json ###
echo "**** generating release.json ****"
cat > "${ROOT_DIR}/release.json" << EOF
{
   "appname": "${APP}",
   "apppic": "${PICTURE}",
   "appfolder": "./",
   "newversion": "5.${ALPINE_VERSION}",
   "baseimage": "${FINALIMAGE}",
   "baseversion": "${BASEIMAGE_VERSION}",
   "body": "Auto-update: Alpine ${ALPINE_VERSION}, Baseimage ${BASEIMAGE_VERSION}",
   "user": "github-actions[bot]"
}
EOF

echo "release.json generated:"
cat "${ROOT_DIR}/release.json"

### GENERATE Dockerfile ###
echo "**** generating Dockerfile ****"
cat > "${ROOT_DIR}/Dockerfile" << 'DOCKERFILE_EOF'
##################################################
# VOD Uploader Docker Container                  #
##################################################
## This file is automatically generated          #
## Do not change manually - use template script  #
##################################################
# shellcheck disable=SC2086
# shellcheck disable=SC2046
DOCKERFILE_EOF

cat >> "${ROOT_DIR}/Dockerfile" << EOF
FROM ${FINALIMAGE}:${BASEIMAGE_VERSION}
LABEL org.opencontainers.image.source="https://github.com/cyb3rgh05t/docker-uploader"
LABEL org.opencontainers.image.description="VOD Uploader container for automated media uploads"
LABEL maintainer="cyb3rgh05t"

ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG ALPINE_VERSION=${BASEIMAGE_VERSION}

RUN \\
  echo "**** update packages ****" && \\
    apk --quiet --no-cache --no-progress update && \\
    apk --quiet --no-cache --no-progress upgrade && \\
  echo "**** install build packages ****" && \\
    apk add -U --update --no-cache bash ca-certificates shadow musl findutils linux-headers coreutils apk-tools busybox && \\
  echo "*** cleanup system ****" && \\
    apk del --quiet --clean-protected --no-progress && \\
    rm -f /var/cache/apk/*

COPY ./root/ /

COPY release.json /var/www/html/release.json

RUN chown abc:abc /var/www/html/release.json && chmod 644 /var/www/html/release.json

ENTRYPOINT ["/init"]
##EOF
EOF

echo "Dockerfile generated!"
echo ""
echo "========================================"
echo "  Update Complete!"
echo "  Alpine: ${ALPINE_VERSION}"
echo "  Baseimage: ${BASEIMAGE_VERSION}"
echo "========================================"
