name: Release VOD Uploader

on:
  push:
    branches:
      - main
      - dev
      - develop
      - nightly
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to use for testing"
        required: true
        default: "nightly"
      force_rebuild:
        description: "Force rebuild without cache"
        required: false
        type: boolean
        default: false

jobs:
  release:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES }}

      - name: Lowercase repository name
        id: repo_name_lowercase
        run: |
          REPO_NAME_LOWERCASE=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME_LOWERCASE=${REPO_NAME_LOWERCASE}" >> "$GITHUB_ENV"
          echo "value=${REPO_NAME_LOWERCASE}" >> "$GITHUB_OUTPUT"

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ steps.repo_name_lowercase.outputs.value }}
          tags: |
            type=ref,event=branch
            type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=${{ github.event.inputs.version }},enable=${{ github.event_name == 'workflow_dispatch' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/amd64,linux/arm64 # Build for amd64 and arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            COMMIT_TAG=${{ github.sha }}
